services:
  Kitchen.PlateIngredients.domain.PlateIngredientRepository:
    class: ../../../../Contexts/Kitchen/PlateIngredients/infrastructure/persistence/FilePlateIngredientRepository
    arguments: []
