services:
  Shared.Logger:
    class: ../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Shared.RabbitMqConfig:
    factory:
      class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMq/RabbitMqConfigFactory
      method: 'createConfig'

  Shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMq/RabbitMqEventBus
    arguments: ['@Shared.RabbitMqConfig', '@Shared.Logger']

  Shared.CommandHandlersInformation:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']

  Shared.EmitterBus:
    class: ../../../../Contexts/Shared/infrastructure/EmitterBus/SocketIo/SocketIoEmitterBus
    arguments: ['@Shared.Logger']
